learning_site/courses/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.course_list, name='course_list'),
    #url(r'^$', views.course_list),
    #url(r'(?P<pk>\d+)/$', views.course_detail),
    path('<course_pk>/t<step_pk>', views.text_detail,
        name='text'),
    path('<course_pk>/q<step_pk>', views.quiz_detail,
        name='quiz'),
    path('<course_pk>/create_quiz', views.quiz_create,
        name = 'create_quiz'),
    path('<course_pk>/edit_quiz/<quiz_pk>', views.quiz_edit,
        name='edit_quiz'),
    path('<quiz_pk>/create_question/<question_type>',
        views.create_question, name='create_question'),
    path('<quiz_pk>/edit_question/<question_pk>', views.edit_question,
        name='edit_question'),
    path('<question_pk>/create_answer', views.answer_form,
        name='create_answer'),
    path('<pk>', views.course_detail, name='detail'),
]

learning_site/learning_site/urls.py
from django.contrib import admin
from django.urls import include, path
#from django.conf.urls import url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from . import views

urlpatterns = [
    path('courses/', include('courses.urls', namespace='courses')),
    path('admin/', admin.site.urls),
    path('suggest/', views.suggestion_view, name='suggestion'),
    path('', views.hello_world, name='home'),
    #url(r'^$', view.hello_world),
]

urlpatterns += staticfiles_urlpatterns()

learning_site/courses/models.py
from django.db import models
#from django.core.urlresolvers import reverse
from django.urls import reverse

# Create your models here.
class Course(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.title


class Step(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField()
    order = models.IntegerField(default=0)
    #course = models.ForeignKey(Course)
    course = models.ForeignKey(Course, on_delete=models.PROTECT)

    class Meta:
        abstract = True
        ordering = ['order',]

    def __str__(self):
        return self.title


class Text(Step):
    content = models.TextField(blank=True, default='')

    def get_absolute_url(self):
        return reverse('courses:text', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id})


class Quiz(Step):
    total_questions = models.IntegerField(default=4)

    class Meta:
        verbose_name_plural = 'Quizzes'

    def get_absolute_url(self):
        return reverse('courses:quiz', kwargs={
            'course_pk': self.course_id,
            'step_pk': self.id,
        })


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.PROTECT)
    order = models.IntegerField(default=0)
    prompt = models.TextField()

    class Meta:
        ordering = ['order',]

    def get_absolute_url(self):
        return self.quiz.get_absolute_url()

    def __str__(self):
        return self.prompt

class MultipleChoiceQuestion(Question):
    shuffle_answers = models.BooleanField(default=False)


class TrueFalseQuestion(Question):
    pass


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.PROTECT)
    order = models.IntegerField(default=0)
    text = models.CharField(max_length=255)
    correct = models.BooleanField(default=False)

    class Meta:
        ordering = ['order',]

    def __str__(self):
        return self.text

learning_site/courses/forms.py
from django import forms

from . import models


class QuizForm(forms.ModelForm):
    class Meta:
        model = models.Quiz
        fields = [
            'title',
            'description',
            'order',
            'total_questions',
        ]


class TrueFalseQuestionForm(forms.ModelForm):
    class Meta:
        model = models.TrueFalseQuestion
        fields = [
            'order',
            'prompt',
        ]


class MultipleChoiceQuestionForm(forms.ModelForm):
    class Meta:
        model = models.MultipleChoiceQuestion
        fields = [
            'order',
            'prompt',
            'shuffle_answers',
        ]

class AnswerForm(forms.ModelForm):
    class Meta:
        model = models.Answer
        fields = [
            'order',
            'text',
            'correct',
        ]


AnswerFormSet = forms.modelformset_factory(
    models.Answer,
    form=AnswerForm,
)

learning_site/courses/views.py
from itertools import chain

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render

from . import forms
from . import models


def course_list(request):
    courses = models.Course.objects.all()
    email = 'questions@learning_site.com'
    return render(request, 'courses/course_list.html', {'courses': courses,
    'email': email})


def course_detail(request, pk):
    #course = Course.objects.get(pk=pk)
    course = get_object_or_404(models.Course, pk=pk)
    steps = sorted(chain(course.text_set.all(), course.quiz_set.all()),
        key=lambda step: step.order)
    return render(request, 'courses/course_detail.html', {
        'course': course,
        'steps': steps
        })


def text_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Text, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/text_detail.html', {'step': step})


def quiz_detail(request, course_pk, step_pk):
    step = get_object_or_404(models.Quiz, course_id=course_pk, pk=step_pk)
    return render(request, 'courses/quiz_detail.html', {'step': step})

@login_required
def quiz_create(request, course_pk):
    course = get_object_or_404(models.Course, pk=course_pk)
    form = forms.QuizForm()
    if request.method == 'POST':
        form = forms.QuizForm(request.POST)
        if form.is_valid():
            quiz = form.save(commit=False)
            quiz.course = course
            quiz.save()
            messages.add_message(request, messages.SUCCESS,"Quiz Added!")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {
        'form': form, 'course':course})


@login_required
def quiz_edit(request, course_pk, quiz_pk):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk, course_id=course_pk)
    form = forms.QuizForm(instance=quiz)
    if request.method == 'POST':
        form = forms.QuizForm(instance=quiz, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(
                form.cleaned_data['title']))
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/quiz_form.html', {
        'form': form, 'course': quiz.course})


@login_required
def create_question(request, quiz_pk, question_type):
    quiz = get_object_or_404(models.Quiz, pk=quiz_pk)
    if question_type == 'tf':
        form_class = forms.TrueFalseQuestionForm
    else:
        form_class = forms.MultipleChoiceQuestionForm
    form = form_class()
    if request.method == 'POST':
        form = form_class(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            messages.success(request, "Added question")
            return HttpResponseRedirect(quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {
        'quiz': quiz,
        'form': form
    })


@login_required
def edit_question(request, quiz_pk, question_pk):
    question = get_object_or_404(models.Question,
        pk=question_pk, quiz_id=quiz_pk)
    if hasattr(question, 'truefalsequestion'):
        form_class = forms.TrueFalseQuestionForm
        question = question.truefalsequestion
    else:
        form_class = forms.MultipleChoiceQuestionForm
        question = question.multiplechoicequestion
    form = form_class(instance=question)

    if request.method == 'POST':
        form = form_class(instance=question, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated question")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/question_form.html', {
        'form': form,
        'quiz': question.quiz
    })

@login_required
def answer_form(request, question_pk):
    question = get_object_or_404(models.Question, pk=question_pk)
    formset = forms.AnswerFormSet(queryset=question.answer_set.all())

    if request.method == 'POST':
        formset = forms.AnswerFormSet(request.POST,
            queryset=question.answer_set.all())
        if formset.is_valid():
            answers = formset.save(commit=False)

            for answer in answers:
                answer.question = question
                answer.save()
            messages.success(request, "Added answers")
            return HttpResponseRedirect(question.quiz.get_absolute_url())
    return render(request, 'courses/answer_form.html', {
        'question': question,
        'formset': formset
    })

learning_site/courses/templates/courses/answer_form.html
{% extends 'courses/layout.html' %}
{% load course_extras %}

{% block title %}{{ question|default:"New Answer" }} | {{ question.quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=question.quiz.course.pk %}">{{ question.quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz' course_pk=question.quiz.course.pk step_pk=question.quiz.pk %}">{{ question.quiz.title }}</a></li>
    <li>{{ question.prompt }}</li>
{% endblock %}

{% block content %}
  <div class="row columns">
    {{ block.super }}
  </div>
  <div class='row columns'>
    <h1>Answers</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      <section>
        {{ formset }}
      </section>
      <input type="submit" class="button" name="" value="Save">
    </form>
  </div>
{% endblock %}

learning_site/courses/templates/courses/course_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ course.title }}{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
        <article>
            <h1 class="">{{ course.title }}</h1>

            <div class="callout secondary">
                {{ course.description|markdown_to_html }}
            </div>

            <dl>
                {% for step in steps %}
                    <dt>
                        <a href="{{ step.get_absolute_url }}">{{ step.title }}</a>
                    </dt>
                    <dd>{{ step.description|markdown_to_html }}</dd>
                {% endfor %}
            </dl>
        </article>
        {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:create_quiz' course_pk=course.id %}" class="button">New Quiz</a>
        {% endif %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/course_list.html
{% extends "courses/layout.html" %}

{% block title %}All{% endblock %}

{% block content %}
    <div class="row columns">
        {{ block.super }}
    </div>
    <div class="row">
        {%  for course in courses %}
            <div class="small-6 columns">
                <div class="callout">
                    <h5><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></h5>
                    <div class="card-copy">
                        {{ course.description }}
                    </div>
                </div>
            </div>

            {% if forloop.counter|divisibleby:"2" %}
                </div>
                <div class="row">
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/course_nav.html
{% for course in courses %} 
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endfor %}

learning_site/courses/templates/courses/layout.html
{% extends "layout.html" %}

{% block title %}Courses | {{ block.super }}{% endblock %}

{% block content %}
    {{ block.super }}
    <ul class="breadcrumbs">
        <li><a href="{% url 'home' %}">Home</a></li>
        <li><a href="{% url 'courses:course_list' %}">Courses</a></li>
        {% block breadcrumbs %}{% endblock %}
    </ul>
{% endblock %}

learning_site/courses/templates/courses/question_form.html
{% extends 'courses/layout.html' %}
{% load course_extras %}

{% block title %}{{ form.instance.prompt|default:"New question" }} | {{ quiz.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=quiz.course.pk %}">{{ quiz.course.title }}</a></li>
    <li><a href="{% url 'courses:quiz' course_pk=quiz.course.pk step_pk=quiz.pk %}">{{ quiz.title }}</a></li>
{% endblock %}

{% block content %}
  <div class="row columns">
    {{ block.super }}
    <h1>{{ form.instance.prompt|default:"Make a new question" }}</h1>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{ form.as_p }}

      {{ formset.management_form }}

      <table role="grid" class="stack hover" style='width: 100%'>

      </table>

      <input type="submit" class="button" name="" value="Save">
    </form>
    {% if user.is_authenticated and form.instance.pk %}
      <hr>
      <a href="{% url 'courses:create_answer' question_pk=form.instance.pk %}" class="button">Answers</a>
    {% endif %}
  </div>
{% endblock %}

learning_site/courses/templates/courses/quiz_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            <ul class="no-bullet">
              {% for question in step.question_set.all %}
              <li>
                <h2>{{ question.prompt }}</h2>
                {% for answer in question.answer_set.all %}
                  <div class="callout">{{ answer.text }}</div>
                {% endfor %}
                {% if user.is_authenticated %}
                  <a href="{% url 'courses:edit_question' question_pk=question.pk quiz_pk=step.pk %}" class="button">Edit</a>
                {% endif %}
              </li>
              {% endfor %}
            </ul>
        </article>
        {% if user.is_authenticated %}
        <hr>
        <a href="{% url 'courses:edit_quiz' course_pk=step.course.pk quiz_pk=step.pk %}" class="button">Edit</a>
        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='mc' %}" class="button">New Multiple Choice Question</a>
        <a href="{% url 'courses:create_question' quiz_pk=step.pk question_type='tf' %}" class="button">New True/False Question</a>
        {% endif %}
    </div>
{% endblock %}

learning_site/courses/templates/courses/quiz_form.html
{% extends 'courses/layout.html' %}

{% block title %}{{ form.instance.title|default:"New Quiz" }} | {{ course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=course.pk %}">{{ course.title }}</a></li>
{% endblock %}

{% block content %}
<div class="row columns">
  {{ block.super }}
  <h1>{{ form.instance.title|default:"Make a new quiz" }}</h1>
  <form class="" action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="button" name="" value="Save">
  </form>
</div>
{% endblock %}

learning_site/courses/templates/courses/step_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block title %}{{ step.title }} | {{ step.course.title }} {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    <li><a href="{% url 'courses:detail' pk=step.course.pk %}">{{ step.course.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}

learning_site/courses/templates/courses/text_detail.html
{% extends "courses/layout.html" %}
{% load course_extras %}

{% block content %}
    <div class="row columns">
        <article>
            {{ block.super }}
            <h1>{{ step.title }}</h1>
            {{ step.content|markdown_to_html }}
        </article>
    </div>
{% endblock %}